import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Copy, Trash2, Sparkles, Loader2, CheckCircle2, Code2 } from 'lucide-react';
import { toast } from 'sonner';

const AiCodeExplainer = () => {
  const [code, setCode] = useState<string>('');
  const [language, setLanguage] = useState<string>('javascript');
  const [explanation, setExplanation] = useState<string>('');
  const [isExplaining, setIsExplaining] = useState(false);
  const [detailLevel, setDetailLevel] = useState<'basic' | 'intermediate' | 'advanced'>('intermediate');

  // Supported languages
  const languages = [
    { value: 'javascript', label: 'JavaScript' },
    { value: 'typescript', label: 'TypeScript' },
    { value: 'python', label: 'Python' },
    { value: 'java', label: 'Java' },
    { value: 'cpp', label: 'C++' },
    { value: 'csharp', label: 'C#' },
    { value: 'go', label: 'Go' },
    { value: 'rust', label: 'Rust' },
    { value: 'php', label: 'PHP' },
    { value: 'ruby', label: 'Ruby' },
  ];

  // Simulated AI code explanation
  const explainCode = async () => {
    if (!code.trim()) {
      toast.error('Please enter code to explain');
      return;
    }

    setIsExplaining(true);

    try {
      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 1500));

      // Generate explanation based on code analysis (demo)
      let explanationText = `# Code Explanation (${detailLevel} level)\n\n`;

      // Detect common patterns
      if (code.includes('function') || code.includes('=>')) {
        explanationText += `## Functions\n\n`;
        explanationText += `This code defines ${detailLevel === 'basic' ? 'one or more functions' : 'function(s) which are reusable blocks of code that perform specific tasks'}.\n\n`;
      }

      if (code.includes('if') || code.includes('else')) {
        explanationText += `## Control Flow\n\n`;
        explanationText += `Conditional logic is used ${detailLevel === 'basic' ? 'to make decisions' : 'to control the execution path based on certain conditions'}.\n\n`;
      }

      if (code.includes('for') || code.includes('while') || code.includes('map') || code.includes('forEach')) {
        explanationText += `## Loops\n\n`;
        explanationText += `Iterative structures are present ${detailLevel === 'basic' ? 'to repeat tasks' : 'to iterate over collections or repeat operations multiple times'}.\n\n`;
      }

      if (code.includes('class') || code.includes('interface') || code.includes('type')) {
        explanationText += `## Data Structures\n\n`;
        explanationText += `Object-oriented or type definitions found ${detailLevel === 'basic' ? 'to organize data' : 'to define custom data structures with properties and methods'}.\n\n`;
      }

      // Add line-by-line analysis for advanced mode
      if (detailLevel === 'advanced') {
        explanationText += `## Line-by-Line Analysis\n\n`;
        const lines = code.split('\n').filter(l => l.trim());
        lines.forEach((line, idx) => {
          if (line.trim()) {
            explanationText += `**Line ${idx + 1}:** \`${line.trim().substring(0, 50)}${line.length > 50 ? '...' : ''}\`\n`;
            explanationText += `- ${getLineExplanation(line, language)}\n\n`;
          }
        });
      }

      explanationText += `## Summary\n\n`;
      explanationText += `This ${language} code ${detailLevel === 'basic' ? 'does something useful' : 'implements functionality that can be understood by analyzing its components. The code structure follows standard patterns and can be maintained or extended as needed'}.\n\n`;

      explanationText += `---\n\n*Explanation generated by SnapTools AI*`;

      setExplanation(explanationText);
      toast.success('Code explained successfully!');
    } catch (error) {
      toast.error('Error explaining code');
    } finally {
      setIsExplaining(false);
    }
  };

  // Helper to explain individual lines
  const getLineExplanation = (line: string, lang: string): string => {
    if (line.includes('//') || line.includes('#')) return 'Contains a comment';
    if (line.includes('import') || line.includes('require')) return 'Imports external module';
    if (line.includes('return')) return 'Returns a value from function';
    if (line.includes('console.log') || line.includes('print')) return 'Outputs data to console';
    if (line.includes('if') || line.includes('else')) return 'Conditional statement';
    if (line.includes('for') || line.includes('while')) return 'Loop iteration';
    if (line.trim().startsWith('//') || line.trim().startsWith('#')) return 'Comment line';
    return 'Code statement';
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(explanation);
    toast.success('Explanation copied to clipboard!');
  };

  const clearAll = () => {
    setCode('');
    setExplanation('');
  };

  const loadExample = () => {
    const examples: Record<string, string> = {
      javascript: `function fibonacci(n) {
  if (n <= 1) return n;
  let a = 0, b = 1;
  for (let i = 2; i <= n; i++) {
    const temp = b;
    b = a + b;
    a = temp;
  }
  return b;
}

console.log(fibonacci(10));`,
      python: `def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

print(quick_sort([3, 6, 8, 10, 1, 2, 1]))`,
      typescript: `interface User {
  id: number;
  name: string;
  email: string;
  isActive: boolean;
}

function getActiveUsers(users: User[]): User[] {
  return users.filter(user => user.isActive);
}

const users: User[] = [
  { id: 1, name: "Alice", email: "alice@example.com", isActive: true },
  { id: 2, name: "Bob", email: "bob@example.com", isActive: false },
];

console.log(getActiveUsers(users));`,
    };

    setCode(examples[language] || examples.javascript);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5" />
            AI Code Explainer - Professional Grade
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Language & Settings */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Programming Language</Label>
              <Select value={language} onValueChange={setLanguage}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {languages.map(lang => (
                    <SelectItem key={lang.value} value={lang.value}>
                      {lang.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Explanation Detail Level</Label>
              <div className="flex gap-2">
                {(['basic', 'intermediate', 'advanced'] as const).map(level => (
                  <Badge
                    key={level}
                    variant={detailLevel === level ? 'default' : 'outline'}
                    className="cursor-pointer capitalize"
                    onClick={() => setDetailLevel(level)}
                  >
                    {level}
                  </Badge>
                ))}
              </div>
              <p className="text-xs text-muted-foreground">
                {detailLevel === 'basic' && 'Simple explanations for beginners'}
                {detailLevel === 'intermediate' && 'Balanced technical detail'}
                {detailLevel === 'advanced' && 'In-depth analysis with line-by-line breakdown'}
              </p>
            </div>
          </div>

          {/* Code Input */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="code-input">Code to Explain</Label>
              <Button variant="ghost" size="sm" onClick={loadExample}>
                Load Example
              </Button>
            </div>
            <Textarea
              id="code-input"
              value={code}
              onChange={(e) => setCode(e.target.value)}
              placeholder="Paste or type your code here..."
              className="min-h-[250px] font-mono text-sm"
            />
            <div className="flex justify-between text-xs text-muted-foreground">
              <span>{code.split('\n').length} lines</span>
              <span>{code.split(/\s+/).filter(w => w.length > 0).length} tokens</span>
            </div>
          </div>

          <Button
            onClick={explainCode}
            disabled={isExplaining || !code.trim()}
            className="w-full"
          >
            {isExplaining ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Analyzing Code...
              </>
            ) : (
              <>
                <Sparkles className="mr-2 h-4 w-4" />
                Explain Code
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Explanation Output */}
      {explanation && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <span className="flex items-center gap-2">
                <CheckCircle2 className="h-5 w-5 text-green-600" />
                Code Explanation
              </span>
              <div className="flex gap-2">
                <Button variant="ghost" size="sm" onClick={copyToClipboard}>
                  <Copy className="h-3 w-3" />
                </Button>
                <Button variant="ghost" size="sm" onClick={clearAll}>
                  <Trash2 className="h-3 w-3" />
                </Button>
              </div>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="p-4 bg-muted rounded-lg">
              <pre className="whitespace-pre-wrap text-sm font-mono">
                {explanation}
              </pre>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Info Card */}
      <Card>
        <CardContent className="pt-6">
          <div className="space-y-4">
            <h3 className="font-semibold flex items-center gap-2">
              <Code2 className="h-4 w-4" />
              About AI Code Explainer
            </h3>
            <div className="text-sm text-muted-foreground space-y-2">
              <p>
                <strong>How it works:</strong> Our AI analyzes your code structure, 
                identifies patterns, and provides clear explanations tailored to your skill level.
              </p>
              <p>
                <strong>Features:</strong> Multiple programming languages, adjustable detail levels, 
                line-by-line analysis, and copy-to-clipboard functionality.
              </p>
              <p>
                <strong>Note:</strong> This demo uses pattern matching. In production, 
                this would connect to advanced AI models like GPT-4, Claude, or Sarvam AI 
                for human-like code explanations.
              </p>
            </div>

            <div className="pt-4 border-t">
              <p className="text-sm font-medium mb-2">Perfect for:</p>
              <div className="flex flex-wrap gap-2">
                {['Learning Code', 'Code Reviews', 'Documentation', 'Debugging', 'Teaching', 'Interviews'].map(use => (
                  <Badge key={use} variant="outline">{use}</Badge>
                ))}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default AiCodeExplainer;
