import { useState } from "react";
import CryptoJS from "crypto-js";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Copy, Loader2, ShieldAlert, Wallet } from "lucide-react";
import { toast } from "sonner";
import {
  ToolCodeBlock,
  ToolMetricGrid,
  ToolPanel,
  ToolTagList,
  ToolWorkbench,
} from "../ai/tool-workbench";

type Network = "ethereum" | "bitcoin" | "solana" | "polygon";

type GeneratedWallet = {
  address: string;
  privateKey: string;
  publicKey: string;
  mnemonic: string;
  path: string;
};

const mnemonicWords = [
  "anchor", "binary", "canvas", "delta", "ember", "fossil", "galaxy", "harbor",
  "island", "jungle", "kernel", "lunar", "matrix", "nectar", "orbit", "pixel",
  "quantum", "radar", "signal", "tidal", "uplift", "vector", "window", "zenith",
];

const hexFromBytes = (bytes: Uint8Array) => Array.from(bytes).map((value) => value.toString(16).padStart(2, "0")).join("");
const randomHex = (bytes: number) => hexFromBytes(globalThis.crypto.getRandomValues(new Uint8Array(bytes)));
const deriveHex = (seed: string, label: string, length = 64) => CryptoJS.SHA256(`${label}:${seed}`).toString().slice(0, length);

const buildMnemonic = (seed: string) => {
  const hash = CryptoJS.SHA256(`mnemonic:${seed}`).toString();
  return Array.from({ length: 12 }, (_, index) => {
    const slice = hash.slice(index * 2, index * 2 + 2);
    return mnemonicWords[parseInt(slice, 16) % mnemonicWords.length];
  }).join(" ");
};

const makeAddress = (network: Network, seed: string) => {
  const core = deriveHex(seed, `${network}:address`, network === "solana" ? 44 : 40);
  if (network === "bitcoin") return `bc1q${core.slice(0, 38)}`;
  if (network === "solana") return core;
  return `0x${core}`;
};

const derivationPath = (network: Network) =>
  network === "bitcoin"
    ? "m/84'/0'/0'/0/0"
    : network === "solana"
      ? "m/44'/501'/0'/0'"
      : "m/44'/60'/0'/0/0";

const CryptoWalletGenerator = () => {
  const [network, setNetwork] = useState<Network>("ethereum");
  const [count, setCount] = useState(1);
  const [mnemonic, setMnemonic] = useState("");
  const [showSecrets, setShowSecrets] = useState(false);
  const [wallets, setWallets] = useState<GeneratedWallet[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  const generateWallets = async () => {
    if (count < 1 || count > 5) {
      toast.error("Choose between 1 and 5 wallets.");
      return;
    }

    setIsGenerating(true);

    try {
      await new Promise((resolve) => setTimeout(resolve, 900));
      const nextWallets = Array.from({ length: count }, (_, index) => {
        const seed = mnemonic.trim() ? `${mnemonic.trim()}#${network}#${index}` : randomHex(32);
        const derivedMnemonic = mnemonic.trim() || buildMnemonic(seed);
        return {
          address: makeAddress(network, seed),
          privateKey: deriveHex(seed, "private"),
          publicKey: deriveHex(seed, "public", 66),
          mnemonic: derivedMnemonic,
          path: derivationPath(network),
        };
      });

      setWallets(nextWallets);
      toast.success(`${nextWallets.length} wallet${nextWallets.length > 1 ? "s" : ""} prepared.`);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <ToolWorkbench
        icon={Wallet}
        eyebrow="Wallet Generator"
        title="Generate deterministic demo wallets in a cleaner operator layout."
        description="This workspace is designed for sandboxed Web3 flows. It generates deterministic demo credentials locally so the UI can be exercised without a backend signer."
        accent="amber"
        badges={["Local-only generation", "Deterministic from mnemonic", "Security-first disclosure toggle"]}
        metrics={[
          { label: "Network", value: network },
          { label: "Wallets", value: wallets.length },
          { label: "Secrets", value: showSecrets ? "Visible" : "Masked" },
        ]}
        aside={
          <div className="space-y-4">
            <ToolPanel title="Supported flows" description="Switch between pure random demo generation and mnemonic-seeded derivation.">
              <ToolTagList tags={["Ethereum", "Bitcoin", "Solana", "Polygon"]} />
            </ToolPanel>
            <ToolPanel title="Important note" description="These credentials are for demo UX and preview environments only.">
              <div className="rounded-3xl border border-amber-500/20 bg-amber-500/5 p-4 text-sm leading-6 text-muted-foreground">
                Never store real funds behind a preview wallet generated by a browser-only demo tool.
              </div>
            </ToolPanel>
          </div>
        }
      >
        <ToolPanel
          title="Generation controls"
          description="Pick a network, set how many wallets you want, and optionally provide a mnemonic to keep outputs reproducible."
        >
          <div className="space-y-5">
            <div className="flex flex-wrap gap-2">
              {(["ethereum", "bitcoin", "solana", "polygon"] as const).map((value) => (
                <Badge
                  key={value}
                  variant={network === value ? "default" : "outline"}
                  className="cursor-pointer rounded-full px-3 py-1 capitalize"
                  onClick={() => setNetwork(value)}
                >
                  {value}
                </Badge>
              ))}
            </div>
            <div className="grid gap-4 md:grid-cols-[160px_minmax(0,1fr)]">
              <div className="space-y-2">
                <Label htmlFor="count">Wallet count</Label>
                <Input
                  id="count"
                  type="number"
                  min="1"
                  max="5"
                  value={count}
                  onChange={(event) => setCount(Math.max(1, Math.min(5, Number(event.target.value) || 1)))}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="mnemonic">Seed mnemonic (optional)</Label>
                <Textarea
                  id="mnemonic"
                  value={mnemonic}
                  onChange={(event) => setMnemonic(event.target.value)}
                  placeholder="Leave empty for random demo wallets, or add a seed phrase for repeatable output."
                  className="min-h-[96px] rounded-3xl border-black/10 bg-white/80 text-sm leading-7 shadow-sm dark:border-white/10 dark:bg-white/[0.03]"
                />
              </div>
            </div>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <label className="flex items-center gap-3 text-sm font-medium">
                <Switch checked={showSecrets} onCheckedChange={setShowSecrets} />
                Reveal secret material in results
              </label>
              <Button onClick={generateWallets} disabled={isGenerating} className="rounded-2xl px-6">
                {isGenerating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wallet className="mr-2 h-4 w-4" />}
                Generate wallets
              </Button>
            </div>
          </div>
        </ToolPanel>
      </ToolWorkbench>

      {wallets.length > 0 ? (
        <ToolPanel title="Generated wallets" description="Each card shows the deterministic output for the current run.">
          <div className="space-y-4">
            {wallets.map((wallet, index) => (
              <div key={wallet.address} className="rounded-[2rem] border border-black/5 bg-white/70 p-5 shadow-sm dark:border-white/10 dark:bg-white/[0.03]">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <div className="text-xs font-black uppercase tracking-[0.24em] text-muted-foreground">Wallet {index + 1}</div>
                    <div className="mt-2 text-lg font-bold">{network}</div>
                  </div>
                  <Button variant="outline" size="sm" onClick={() => navigator.clipboard.writeText(wallet.address).then(() => toast.success("Address copied."))}>
                    <Copy className="mr-2 h-4 w-4" />
                    Copy address
                  </Button>
                </div>
                <div className="mt-4 space-y-4">
                  <ToolCodeBlock value={wallet.address} className="max-h-none bg-slate-900 p-4" />
                  <ToolMetricGrid
                    metrics={[
                      { label: "Path", value: wallet.path },
                      { label: "Mnemonic words", value: wallet.mnemonic.split(" ").length },
                      { label: "Key display", value: showSecrets ? "Expanded" : "Masked" },
                    ]}
                  />
                  <div className="grid gap-4 md:grid-cols-2">
                    <div>
                      <div className="mb-2 text-xs font-bold uppercase tracking-[0.22em] text-muted-foreground">Mnemonic</div>
                      <div className="rounded-3xl border border-black/5 bg-background p-4 text-sm leading-7 dark:border-white/10">
                        {wallet.mnemonic}
                      </div>
                    </div>
                    <div>
                      <div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.22em] text-muted-foreground">
                        <ShieldAlert className="h-3.5 w-3.5" />
                        Key material
                      </div>
                      <div className="rounded-3xl border border-black/5 bg-background p-4 font-mono text-xs leading-6 dark:border-white/10">
                        <div>Public: {wallet.publicKey}</div>
                        <div className="mt-3">
                          Private: {showSecrets ? wallet.privateKey : `${wallet.privateKey.slice(0, 10)}••••••••••••••••`}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </ToolPanel>
      ) : null}
    </div>
  );
};

export default CryptoWalletGenerator;
